### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by ArenasAgustin** [ArenasAgustin/Juegos-HTML#1]
- [x] Fix styles cross
- [ ] New levels and upgrade levels
- [ ] Change textures dungeon
- [ ] More enemies
- [ ] Add pause and play
- [ ] Be able to attack enemies
- [x] Add manifest.json
- [x] Icom
